#### Tensor 이해 - 생성
 - Tensor란? 
    * pytorch에서 데이터를 저장하는 객체
    * 모델에 입력/출력 데이터 형태
 - 개발 버전 : torch v 2.4.1

- 이제부터 들어가는 차원이 3차원 4차원 이런식으로 들가기에 차원 맞추는걸 주의할 것!

In [6]:
# 모듈 로딩
import torch

# 이제 할때는 모듈의 버전을 밑에 체크해놓기
print(f'torch v. {torch.__version__}')

torch v. 2.4.1


In [7]:
# 함수기능: 텐서 속성 정보 출력 함수
def printInfo(obj, obj_name):
    print(f'\n[{obj_name}]')
    print(f'shape : {obj.shape}')
    print(f'ndim : {obj.ndim}차원')
    print(f'dtype : {obj.dtype}')
    print(f'device : {obj.device}')
    print(f'data :\n{obj.data}') 

- 텐서 생성 [1] : torch.tensor() > 메서드

In [9]:
## 데이터 1개 즉, 스칼라
ten1 = torch.tensor(10)  # >> 메모리 8칸 사용
ten2 = torch.tensor([22,33,44])
ten3 = torch.tensor([[90,91],[80,81], [70,71]])

ten1_1 = torch.tensor(10, dtype=torch.uint8) # >> 메모리 한칸 사용

# 텐서 정보 출력
printInfo(ten1, 'ten1')
printInfo(ten1_1, 'ten1_1')
printInfo(ten2, 'ten2')
printInfo(ten3, 'ten3')


[ten1]
shape : torch.Size([])
ndim : 0차원
dtype : torch.int64
device : cpu
data :
10

[ten1_1]
shape : torch.Size([])
ndim : 0차원
dtype : torch.uint8
device : cpu
data :
10

[ten2]
shape : torch.Size([3])
ndim : 1차원
dtype : torch.int64
device : cpu
data :
tensor([22, 33, 44])

[ten3]
shape : torch.Size([3, 2])
ndim : 2차원
dtype : torch.int64
device : cpu
data :
tensor([[90, 91],
        [80, 81],
        [70, 71]])


In [10]:
## 데이터 1개 즉, 벡터 1D
ten1 = torch.tensor([10]) # 괄호로 1차원 가능
printInfo(ten1, 'ten1')


[ten1]
shape : torch.Size([1])
ndim : 1차원
dtype : torch.int64
device : cpu
data :
tensor([10])


In [11]:
ten1 = torch.tensor([]) # > 차원이 될수있다 원소가 없을뿐
printInfo(ten1, 'ten1')


[ten1]
shape : torch.Size([0])
ndim : 1차원
dtype : torch.float32
device : cpu
data :
tensor([])


In [12]:
## 데이터 1개 즉, 벡터 2D
ten1 = torch.tensor([[10]]) 
printInfo(ten1, 'ten1')

ten2 = torch.tensor([[10], [20]]) 
printInfo(ten2, 'ten2')

ten3 = torch.tensor([[10, 20]]) 
printInfo(ten3, 'ten3')


[ten1]
shape : torch.Size([1, 1])
ndim : 2차원
dtype : torch.int64
device : cpu
data :
tensor([[10]])

[ten2]
shape : torch.Size([2, 1])
ndim : 2차원
dtype : torch.int64
device : cpu
data :
tensor([[10],
        [20]])

[ten3]
shape : torch.Size([1, 2])
ndim : 2차원
dtype : torch.int64
device : cpu
data :
tensor([[10, 20]])


In [16]:
## 데이터 1개 즉, 벡터 ND >> 차원을 읽을때 뒤에서 앞으로 읽어야 한다. [4D(3D가 몇개냐), 3D(2차원이 장), 행, 열] 요래  >>> []을 보는게 차원수를 세기에 좋다
ten1 = torch.tensor([[[[10]]]])  
printInfo(ten1, 'ten1')

ten1 = torch.tensor([[[10]]],dtype=torch.uint8) 
printInfo(ten1, 'ten1')

ten1 = torch.tensor([[[10]],[[10]],[[10]]],dtype=torch.uint8) 
printInfo(ten1, 'ten1')


[ten1]
shape : torch.Size([1, 1, 1, 1])
ndim : 4차원
dtype : torch.int64
device : cpu
data :
tensor([[[[10]]]])

[ten1]
shape : torch.Size([1, 1, 1])
ndim : 3차원
dtype : torch.uint8
device : cpu
data :
tensor([[[10]]], dtype=torch.uint8)

[ten1]
shape : torch.Size([3, 1, 1])
ndim : 3차원
dtype : torch.uint8
device : cpu
data :
tensor([[[10]],

        [[10]],

        [[10]]], dtype=torch.uint8)


In [ ]:
# 텐서 특정값으로 채워야 할 경우
