#### Tensor 이해 - 형 변환

In [1]:
# 모듈 로딩
import torch

# 이제 할때는 모듈의 버전을 밑에 체크해놓기
print(f'torch v. {torch.__version__}')

torch v. 2.4.1


- 방법 [1] type(torch.원하는 type)

In [2]:
# tensor 생성
dataTS1 = torch.tensor([1,3,5])
dataTS1, dataTS1.dtype

(tensor([1, 3, 5]), torch.int64)

In [3]:
# int64 > float32
dataTS1.type(torch.float32)

tensor([1., 3., 5.])

In [4]:
# 저장 안하면 안 바뀜
dataTS1.dtype

torch.int64

In [5]:
dataTS11 = dataTS1.type(torch.float32)
dataTS11, dataTS11.dtype

(tensor([1., 3., 5.]), torch.float32)

방법[2] - 타입명() 

In [10]:
# int64 > float32
dataTS11 = dataTS1.float()
dataTS11, dataTS11.dtype

(tensor([1., 3., 5.]), torch.float32)

In [13]:
# int64>> bool
dataTS11 = dataTS1.bool()
dataTS11, dataTS11.dtype

(tensor([True, True, True]), torch.bool)

- 방법[3] to(dtype = OOO, device = OOO)

In [17]:
# int64 => int 8
dataTS1.to(dtype=torch.int8,
           device = 'cuda' if torch.cuda.is_available() else 'cpu')

tensor([1, 3, 5], dtype=torch.int8)

In [16]:
## tmffkdlt
dataTS1[0], dataTS1[-1]

(tensor(1), tensor(5))