#### Tensor 변환
- torch.as_tensor()
    * 동일 타입과 디바이스를 가진 데이터 존재 ==> view 즉, 데이터 공유
    * 다른 타입 똔느 다른 디바이스를 가진 데이터 존재 ==> copy 즉, 생성
    * view tensor 또는 copy tensor 변환

In [1]:
# 모듈 로딩
import torch

# 이제 할때는 모듈의 버전을 밑에 체크해놓기
print(f'torch v. {torch.__version__}')

torch v. 2.4.1


- Python 객체 ==> Tensor 변환

In [2]:
### list ==> Tensor
data = list(range(1,10))

In [3]:
## torch.as_tensor()
dataTS = torch.as_tensor(data, dtype=torch.int8)
dataTS, dataTS.shape, dataTS.ndim, dataTS.dtype # 데이터 형태를 지정하면 그 지정한 형태로 지정된다. 지정 안하면 그냥 그 쪽에서 가장 큰 값을 저장한다. 데이터 손실을 막기위해 

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8),
 torch.Size([9]),
 1,
 torch.int8)

In [4]:
data[0] = 100

In [5]:
data, dataTS

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

- Numpy ndarray 객체 ==> Tensor 변환

In [6]:
import numpy as np

In [7]:
arr1 = np.array([1,2,3])
arr1, arr1.ndim, arr1.dtype 

(array([1, 2, 3]), 1, dtype('int32'))

In [8]:
arrTS = torch.as_tensor(arr1)
arrTS

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
arr1[0] = 77

In [10]:
arr1, arrTS  # >> 이건 view 방식 >> sharing되어서 값이 변경된다. 
## 텐서로 새로만들면 sharing되지않고 copy되어 변경된다.

(array([77,  2,  3]), tensor([77,  2,  3], dtype=torch.int32))

- Numpy ndarray => Tensor 변환 : from_numpy()

In [19]:
arr1 = np.array([[5,7,9],[1,2,3]], dtype=np.float32)  #>>> np하냐 안하냐 차이 있나?
print(arr1)
print(f'데이터 저장 메모리 : {arr1.data} ')
print(f'원소/요소 개수     : {arr1.size}')
print(f'원소/요소 1개 크기 : {arr1.itemsize}')
print(f'타입              : {arr1.dtype}')
print(f'방향              : {arr1.strides}')

[[5. 7. 9.]
 [1. 2. 3.]]
데이터 저장 메모리 : <memory at 0x000001F2E884CC70> 
원소/요소 개수     : 6
원소/요소 1개 크기 : 4
타입              : float32
방향              : (12, 4)


In [22]:
arr1 = np.array([[5,7,9],[1,2,3]], dtype=np.float16)  # 저장 바이트에 따라서 달라지는 것이 있다 
print(arr1)
print(f'데이터 저장 메모리 : {arr1.data}')
print(f'원소/요소 개수     : {arr1.size}')
print(f'원소/요소 1개 크기 : {arr1.itemsize}')
print(f'타입              : {arr1.dtype}')
print(f'방향              : {arr1.strides}')

[[5. 7. 9.]
 [1. 2. 3.]]
데이터 저장 메모리 : <memory at 0x000001F2E884CC70>
원소/요소 개수     : 6
원소/요소 1개 크기 : 2
타입              : float16
방향              : (6, 2)


In [17]:
arrTS = torch.from_numpy(arr1)
arrTS

tensor([[5., 7., 9.],
        [1., 2., 3.]], dtype=torch.float16)