#### Tensor 이해

In [1]:
# 모듈 로딩
import torch

# 이제 할때는 모듈의 버전을 밑에 체크해놓기
print(f'torch v. {torch.__version__}')

torch v. 2.4.1


- 타입 지정 Tensor 클래스 활용
    * 데이터 타이비을 설정 후 생성
    * 언제 쓰냐? 
    >> 데이터 사이즈 설정한 텐서 생성 시 사용     
        데이터의 자료형 변환한 텐서 생성 시 사용

In [2]:
### 정수형 텐서 생성
data = [1.4, 2.8, 3.1]

In [7]:
### 1바이트 정수형 텐서 생성
dataTS1 = torch.CharTensor(data)
dataTS11 =  torch.tensor(data, dtype=torch.int8)
print(dataTS1, dataTS11, sep='\n')

tensor([1, 2, 3], dtype=torch.int8)
tensor([1, 2, 3], dtype=torch.int8)


C:\Users\KDP-23\AppData\Local\Temp\ipykernel_19928\698855462.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1 = torch.CharTensor(data)
C:\Users\KDP-23\AppData\Local\Temp\ipykernel_19928\698855462.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS11 =  torch.tensor(data, dtype=torch.int8)


In [6]:
dataTS1 = torch.ShortTensor(data)
dataTS11 =  torch.tensor(data, dtype=torch.int16)
print(dataTS1, dataTS11, sep='\n')

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int16)


C:\Users\KDP-23\AppData\Local\Temp\ipykernel_19928\3984467967.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1 = torch.ShortTensor(data)
C:\Users\KDP-23\AppData\Local\Temp\ipykernel_19928\3984467967.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS11 =  torch.tensor(data, dtype=torch.int16)


In [9]:
### 논리형 Tensor 생성
dataTS1 = torch.BoolTensor(data) # 클래스 사용
dataTS11 =  torch.tensor(data, dtype=torch.bool) # 메서드를사용해서 형태 선언
print(dataTS1, dataTS11, sep='\n') # 0 제외하고 True

tensor([True, True, True])
tensor([True, True, True])


In [11]:
### 실수형 Tensor 생성
dataTS1 = torch.DoubleTensor(data) # 클래스 사용
dataTS11 =  torch.tensor(data, dtype=torch.float64)
print(dataTS1, dataTS11, sep='\n') 

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)


- Tensor 저장 및 실행 위치 설정 ==>  속성 device 설정

In [15]:
### 저장 및 실행 위치 >> CPU / GPU

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
DEVICE ## 모든 이름이 대문자다 다른언어에서는 >> 지역번호, 국가 코드 변할수없는 값(바꿀 수 없는 값) >>> 상수


'cpu'

In [16]:
### 실수형 Tensor 생성
dataTS1 = torch.DoubleTensor(data) # 클래스 사용
dataTS11 =  torch.tensor(data, dtype=torch.float64, device=DEVICE) # 세팅된 디바이스 따라간다.
print(dataTS1, dataTS11, sep='\n') 
### 왜 이렇게 하냐 >> 많은 일을해야 하기 때문

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
