#### 피쳐 전처리
- 수치형 피쳐 전처리 ==> 스케일링
- 범주형 피쳐 전처리 ==> 인코딩

In [98]:
# 모듈로딩
from sklearn.preprocessing import LabelEncoder

In [99]:
items = ['TV','냉장고','선풍기','에어컨']

In [100]:
# 라벨/ 정수 인코더 인스턴스 생성
lencoder = LabelEncoder()

In [101]:
# 라벨/정수 인코더의 범위 및 맵핑 작업
lencoder.fit(items)

LabelEncoder()

In [102]:
# 라벨/ 정수값으로 변환
lencoder.transform(items)

array([0, 1, 2, 3])

In [103]:
### one-hot-Encoder 원-핫-인코더
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [104]:
# 인코더 인스턴스 생성
ohEncoder = OneHotEncoder()

In [105]:
# 원핫 인코더의 범위 및 맵핑 작업
# fit(2D)
arr_items = np.array(items).reshape(-1,1) # >> 4행 1열
print(arr_items.shape)


ohEncoder.fit(arr_items)

(4, 1)


OneHotEncoder()

In [106]:
# 원핫인코딩으로 변환
oh_items = ohEncoder.transform(arr_items)
type(oh_items)

scipy.sparse._csr.csr_matrix

In [107]:
oh_items.toarray()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [108]:
#### 점수인코딩 ==> 범주형 피쳐
from sklearn.preprocessing import OrdinalEncoder

In [109]:
data=[['male','C','child'], ['female','s','child']]

In [110]:
# 정수인코더 인스턴스 생성
odEncoder = OrdinalEncoder()

In [111]:
# 정수인코딩 벙위 및 맵핑 진행
odEncoder.fit(data) # fit(2D)

OrdinalEncoder()

In [112]:
# 범주 피쳐 ==> 정수 피쳐 변환
odEncoder.transform(data)

array([[1., 0., 0.],
       [0., 1., 0.]])