### 다차원 배열의 구조 변경하기

#### - 내부 조작 함수

##### >> 정렬 함수

In [3]:
import pandas as pd
import numpy as np

In [4]:
# 정렬 함수 - sort() > 기본 오름차순
a = np.linspace(1,6,6, dtype=np.int32)
a

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [7]:
np.random.shuffle(a)
a

array([1, 6, 2, 4, 3, 5], dtype=int32)

In [8]:
b = np.sort(a)
b

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [15]:
# 정렬 함수 : argsort
bb=b.copy()
bb

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [22]:
np.random.shuffle(bb)
bb

array([3, 1, 2, 4, 6, 5], dtype=int32)

In [23]:
c= np.argsort(bb)
c

array([1, 2, 0, 3, 5, 4])

In [25]:
bb[c[0]]

np.int32(1)

In [26]:
bb[c[1]]

np.int32(2)

In [ ]:
# 배열 클래스 변경

In [27]:
# 배열의 값 변경
o = np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
o.fill(100)

In [29]:
o

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [32]:
a= np.full(o.shape, 99.)
a

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [35]:
# 취이 변경 및 이동
array = np.arange(4).reshape(2,2)

In [36]:
array

array([[0, 1],
       [2, 3]])

In [38]:
# 배열 내의 원소 점검
m = np.random.randn(3,5)
m

array([[-0.32012959,  0.2068705 ,  1.68880081, -0.73835674,  0.97992233],
       [ 0.74929235,  0.27511805,  0.23215504,  2.06155996,  0.61562433],
       [-0.82666458, -1.3055271 ,  2.20025549,  0.21197826, -0.83349032]])

In [39]:
np.isreal(m)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
np.isinf(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [41]:
np.isnan(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

#### >> 배열의 padding 처리

In [42]:
# 패딩
x=np.arange(1,5).reshape(2,2) # >>> () 이거랑  (()) 이거랑 뭔 차인겨?? 둘다 되는디??
x 

array([[1, 2],
       [3, 4]])

In [43]:
z= np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
z[:2 , :2] = x
z

array([[1., 2., 0.],
       [3., 4., 0.],
       [0., 0., 0.]])

In [47]:
# 패딩 함수
np.pad(x,0,"constant")

array([[1, 2],
       [3, 4]])

In [48]:
np.pad(x,(0,1),"constant")

array([[1, 2, 0],
       [3, 4, 0],
       [0, 0, 0]])

In [49]:
np.pad(x,(1,0),"constant")

array([[0, 0, 0],
       [0, 1, 2],
       [0, 3, 4]])

In [50]:
np.pad(x,(1,1),"constant")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [51]:
np.pad(x,(3,3),"constant")

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [52]:
# "edge"
np.pad(x,(0,1),"edge")

array([[1, 2, 2],
       [3, 4, 4],
       [3, 4, 4]])

In [53]:
np.pad(x,(1,0),"edge")

array([[1, 1, 2],
       [1, 1, 2],
       [3, 3, 4]])

In [54]:
np.pad(x,(1,1),"edge")

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [56]:
np.pad(x,(3,3),"edge")

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4]])

In [60]:
# np.pad("maximum","minmum","mean","median")

np.pad(x,(3,3),"maximum")

array([[4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4]])

In [59]:
np.pad(x,(3,3),"minimum")

array([[1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [3, 3, 3, 3, 4, 3, 3, 3],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1]])

In [61]:
np.pad(x,(1,1),"mean")

array([[2, 2, 3, 2],
       [2, 1, 2, 2],
       [4, 3, 4, 4],
       [2, 2, 3, 2]])

In [62]:
np.pad(x,(3,3),"mean")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])

In [63]:
np.pad(x,(3,3),"median")

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])