### 수학 함수 알아보기

#### - 산술 함수

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
# 소수점 이하 처리 
## 소수점 이하를 버리는 fix(), trunc() 
a=np.array([3.14, 4.32])
np.fix(a)

array([3., 4.])

In [15]:
np.trunc(a)

array([3., 4.])

In [17]:
b = np.array([3.14, 4.52])

# 올림 ceil()
np.ceil(b)

array([4., 5.])

In [18]:
# 버림 floor()
np.floor(b)

array([3., 4.])

In [4]:
# 산술 연산

In [5]:
# 부호, 절대값

In [6]:
# 제곱근,  제곱


#### - 논리 및 비교 연산


In [7]:
# 논리 연산

In [8]:
# 비교 연산

In [9]:
# 수열의 합

In [10]:
# 수열의 곱

In [11]:
# 결측값 계산

#### - 지수와 로그 함수 이해하기

In [19]:
# 자연 상수(e)의 지수

np.exp(0) # np.exp(e의 지수) 

np.float64(1.0)

In [20]:
np.exp(-2)

np.float64(0.1353352832366127)

In [21]:
1/ np.exp(2)

np.float64(0.1353352832366127)

In [23]:
a = np.power(np.e,2)
a

np.float64(7.3890560989306495)

In [25]:
b = np.power(np.e,3)
b

np.float64(20.085536923187664)

In [26]:
np.exp(5)

np.float64(148.4131591025766)

In [27]:
np.exp(2+3)

np.float64(148.4131591025766)

In [28]:
a*b

np.float64(148.41315910257657)

In [29]:
np.power(np.e,5)

np.float64(148.41315910257657)

In [30]:
# 지수 함수

x= np.arange(5)
x

array([0, 1, 2, 3, 4])

In [31]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [32]:
np.power(np.e,x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [33]:
np.exp2(x)

array([ 1.,  2.,  4.,  8., 16.])

In [34]:
np.power(2,x)

array([ 1,  2,  4,  8, 16])

In [35]:
np.expm1(5)

np.float64(147.4131591025766)

In [36]:
np.exp(5)-1

np.float64(147.4131591025766)

In [38]:
# 로그함수

x= np.arange(10000,1000000,100000)
x

array([ 10000, 110000, 210000, 310000, 410000, 510000, 610000, 710000,
       810000, 910000])

In [39]:
np.log(x)

array([ 9.21034037, 11.60823564, 12.25486281, 12.64432758, 12.92391244,
       13.142166  , 13.32121424, 13.47302025, 13.60478953, 13.72119988])

In [40]:
np.ceil(np.log(x)) # ceil 올림

array([10., 12., 13., 13., 13., 14., 14., 14., 14., 14.])

In [41]:
np.exp(9.21034037)

np.float64(9999.99998023818)

In [42]:
np.allclose(np.exp(9.21034037), 10000)

True

#### - 집합 이해하기

In [44]:
# 집합
x = np.array([[1,2,3],[4,5,6],[3,4,5]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

In [45]:
np.unique(x)

array([1, 2, 3, 4, 5, 6])

In [46]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [49]:
np.isin(5,y)

array(True)

In [51]:
np.isin(4,y)

array(True)

In [53]:
np.isin([3,4,5],y)

array([ True,  True, False])

#### - 삼각함수 이해하기

In [ ]:
# 넘어가~~~