### 확률, 통계 함수 알아보기 

#### - 확률분포 함수

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# 균등분포
x= np.random.randint(3,10,size=10)
x

array([8, 7, 5, 8, 7, 3, 8, 8, 5, 5], dtype=int32)

In [4]:
y = np.random.randint(3,10,size= (3,3))
y

array([[4, 6, 9],
       [9, 8, 4],
       [5, 6, 4]], dtype=int32)

In [6]:
x= np.random.uniform(0,1,10)
x

array([0.74599848, 0.47145985, 0.91627115, 0.4206044 , 0.46631601,
       0.20100415, 0.04135902, 0.11940334, 0.74883497, 0.29704373])

In [8]:
y= np.random.uniform(10,20,(3,3))
y

array([[11.81884317, 19.79771678, 18.19750441],
       [17.24630675, 12.09785891, 18.32814652],
       [16.68875686, 14.48689708, 12.19059211]])

#### - 통계 함수

In [9]:
# 범위
a= np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [10]:
np.max(a), np.min(a)

(np.int64(9), np.int64(2))

In [11]:
np.max(a) - np.min(a)

np.int64(7)

In [12]:
np.ptp(a)

np.int64(7)

In [13]:
np.percentile(a,50)

np.float64(4.0)

In [15]:
# 평균과 중앙값
d = np.array([3,4,2,3,8,9,5])
np.median(d)

np.float64(4.0)

In [16]:
np.sort(d)

array([2, 3, 3, 4, 5, 8, 9])

In [17]:
# 평균 구하는 방법1
d.mean()

np.float64(4.857142857142857)

In [18]:
#방법2
np.mean(d)

np.float64(4.857142857142857)

In [20]:
#방법3
np.average(d)

np.float64(4.857142857142857)

In [24]:
# 모분산, 모표준편차
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [ ]:
# 표본분산, 표본 표준편차

In [ ]:
# 상관계수, 공분산