### 방정식, 미적분, 합성곱 알아보기

#### -  방정식 알아보기


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# 방정식 처리
ef = np.array([1,-2,1])

In [6]:
p = np.poly1d(ef)

In [7]:
p

poly1d([ 1, -2,  1])

In [8]:
print(p)

   2
1 x - 2 x + 1


In [9]:
print(type(p), 
      p.variable, 
      p.order,
      p.coef, 
      p.coefficients,
      p.coeffs, 
      p.roots, sep='\n')

<class 'numpy.poly1d'>
x
2
[ 1 -2  1]
[ 1 -2  1]
[ 1 -2  1]
[1.+6.68896751e-09j 1.-6.68896751e-09j]


In [10]:
p(0)

np.int64(1)

In [11]:
np.polyval([1,-2,1],0)

np.int64(1)

In [12]:
np.polyval([1,-2,1],5)

np.int64(16)

In [13]:
# 연립 방정식
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
a,b

(array([[3, 1],
        [1, 2]]),
 array([9, 8]))

In [14]:
x = np.linalg.solve(a,b)
x

array([2., 3.])

In [15]:
np.allclose (np.dot(a, x), b)

True

In [16]:
A = np.array([[1,0,0],[1,1,1],[6,7,0]])
B = np.array([0,24,0])

In [17]:
# 역행렬 사용
A_1 = np.linalg.inv(A)
A_1

array([[ 1.00000000e+00,  0.00000000e+00, -2.31296463e-17],
       [-8.57142857e-01, -0.00000000e+00,  1.42857143e-01],
       [-1.42857143e-01,  1.00000000e+00, -1.42857143e-01]])

In [18]:
x = np.dot(A_1, B)
x

array([ 0.,  0., 24.])

In [19]:
np.allclose(np.dot(A_1, B), x)

True

In [20]:
# 함수 사용
np.linalg.solve(A,B)

array([ 0., -0., 24.])

In [21]:
np.allclose(np.dot(A_1, B),x)

True

In [22]:
# Istsq 함수로 연립 방정식 풀기
np.linalg.matrix_rank(A)

np.int64(3)

In [23]:
x, resid, rank, singulr = np.linalg.lstsq(A,B, rcond= -1)
x

array([ 3.05504346e-15, -2.56636673e-15,  2.40000000e+01])

In [24]:
np.allclose(np.dot(A,x),B)

True

#### - 차분, 미분과 적분

In [25]:
# diff 함수 알아보기
x = np.array([1,2,4,7,10])
x

array([ 1,  2,  4,  7, 10])

In [26]:
# 하나의 배열에 내의 원소들 간의 차를 구하는 차분 함수 diff
np.diff(x)

array([1, 2, 3, 3])

In [27]:
np.diff(x, n=2) 
# n=2는 왜함? diff에서 한번더 한건가?

array([1, 1, 0])

In [28]:
c=np.diff(x)
c

array([1, 2, 3, 3])

In [29]:
np.diff(c)

array([1, 1, 0])

In [30]:
# diff 함수로 미분

x = np.array([1,2,3,4,5,6])
dx = np.diff(x)
dx

array([1, 1, 1, 1, 1])

In [31]:
y= np.array([2,4,6,8,10,12])
dy= np.diff(y)
dy

array([2, 2, 2, 2, 2])

In [32]:
dydx = np.zeros(y.shape, np.float64) # 야는 또 뭐꼬?
dydx

array([0., 0., 0., 0., 0., 0.])

In [33]:
dydx[:-1] = dy/dx #이게 뭔데?
dydx

array([2., 2., 2., 2., 2., 0.])

In [34]:
dydx[-1] = (y[-1] - y[-2]) / (x[-1] - x[-2])

In [35]:
dydx

array([2., 2., 2., 2., 2., 2.])

In [36]:
np.gradient(y) # 위에 필요없이 함수로 사용가능하다

array([2., 2., 2., 2., 2., 2.])

In [37]:
# 다항식으로 미분하기
# 다항식 객체를 미분할 때는 polyder 함수를 사용
a = np.array([1,-2,1])
p = np.poly1d(a)
print(p)

   2
1 x - 2 x + 1


In [38]:
d = np.polyder(p)
d

poly1d([ 2, -2])

In [39]:
d(10)

np.int64(18)

In [40]:
# 중앙 차분으로 미분 구하기
x = 10 
def f(x):
    return x**2

In [41]:
def numerical_differentiation(f,x):
    delta_x= 1e-7
    return (f(x+delta_x) - f(x-delta_x)) / (delta_x*2)

In [42]:
nd = numerical_differentiation(f,x)
nd

19.99999987845058

In [43]:
# gradient로 위에꺼 필요없이 미분가능
y= (x**2) +1

In [44]:
x= np.linspace(0,10)
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [45]:
dydx = np.gradient(y)
dydx

()

In [46]:
np.gradient(y,2)

()

In [47]:
# 적분 알아보기

x2 = np.arange(5)
x2

array([0, 1, 2, 3, 4])

In [48]:
y2 = x2**2
np.trapezoid(y2,x=x2) # 버전업되면서 trapz >>> trapezoid로 대채됨

np.float64(22.0)

In [49]:
from scipy.integrate import quad

In [50]:
x2 = lambda x:x**2
quad(x2, 0, 4)

(21.333333333333336, 2.368475785867001e-13)

#### - 합성곱 및 필터링 알아보기

In [51]:
# 1D 합성곱 함수 
# 2D 합성곱 함수 

In [52]:
# 필터링
B= [[3,4,5,2,3],
    [3,5,1,2,7],
    [2,2,5,6,7]]
B = np.array(B)
B

array([[3, 4, 5, 2, 3],
       [3, 5, 1, 2, 7],
       [2, 2, 5, 6, 7]])

In [53]:
from scipy.ndimage.filters import maximum_filter, minimum_filter

C:\Users\KDP-23\AppData\Local\Temp\ipykernel_4228\4125082450.py:1: DeprecationWarning: Please import `maximum_filter` from the `scipy.ndimage` namespace; the `scipy.ndimage.filters` namespace is deprecated and will be removed in SciPy 2.0.0.
  from scipy.ndimage.filters import maximum_filter, minimum_filter
C:\Users\KDP-23\AppData\Local\Temp\ipykernel_4228\4125082450.py:1: DeprecationWarning: Please import `minimum_filter` from the `scipy.ndimage` namespace; the `scipy.ndimage.filters` namespace is deprecated and will be removed in SciPy 2.0.0.
  from scipy.ndimage.filters import maximum_filter, minimum_filter


In [54]:
maximum_filter(B, size=(2,2))

array([[3, 4, 5, 5, 3],
       [3, 5, 5, 5, 7],
       [3, 5, 5, 6, 7]])

In [55]:
maximum_filter(B, footprint=np.ones((3,3)))

array([[5, 5, 5, 7, 7],
       [5, 5, 6, 7, 7],
       [5, 5, 6, 7, 7]])

In [56]:
minimum_filter(B, size=(2,2))

array([[3, 3, 4, 2, 2],
       [3, 3, 1, 1, 2],
       [2, 2, 1, 1, 2]])

In [57]:
minimum_filter(B, footprint=np.ones((3,3)))

array([[3, 1, 1, 1, 2],
       [2, 1, 1, 1, 2],
       [2, 1, 1, 1, 2]])

In [58]:
# 풀링
from skimage import measure as skm

In [60]:
sk = skm.block_reduce(B, (1,1), np.max)
sk

array([[3, 4, 5, 2, 3],
       [3, 5, 1, 2, 7],
       [2, 2, 5, 6, 7]])

In [61]:
sk = skm.block_reduce(B, (1,2), np.max)
sk

array([[4, 5, 3],
       [5, 2, 7],
       [2, 6, 7]])

In [62]:
sk = skm.block_reduce(B, (2,1), np.max)
sk

array([[3, 5, 5, 2, 7],
       [2, 2, 5, 6, 7]])