#### Tensor 변환

In [1]:
# 모듈 로딩
import torch

# 이제 할때는 모듈의 버전을 밑에 체크해놓기
print(f'torch v. {torch.__version__}')

torch v. 2.4.1


- Python 객체 ==> Tensor 변환

In [2]:
### list ==> Tensor
data = list(range(1,10))

In [3]:
## torch.as_tensor()
dataTS = torch.as_tensor(data, dtype=torch.int8)
dataTS, dataTS.shape, dataTS.ndim, dataTS.dtype # 데이터 형태를 지정하면 그 지정한 형태로 지정된다. 지정 안하면 그냥 그 쪽에서 가장 큰 값을 저장한다. 데이터 손실을 막기위해 

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8),
 torch.Size([9]),
 1,
 torch.int8)

In [4]:
data[0] = 100

In [5]:
data, dataTS

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

- Numpy ndarray 객체 ==> Tensor 변환

In [6]:
import numpy as np

In [7]:
arr1 = np.array([1,2,3])
arr1, arr1.ndim, arr1.dtype 

(array([1, 2, 3]), 1, dtype('int32'))

In [8]:
arrTS = torch.as_tensor(arr1)
arrTS

tensor([1, 2, 3], dtype=torch.int32)

In [9]:
arr1[0] = 77

In [10]:
arr1, arrTS

(array([77,  2,  3]), tensor([77,  2,  3], dtype=torch.int32))