#### 턴더 생성 여러 메서드

In [44]:
# 모듈 로딩
import torch

# 이제 할때는 모듈의 버전을 밑에 체크해놓기
print(f'torch v. {torch.__version__}')

torch v. 2.4.1


- Tensor생성 [2] torch.rand() >>> 랜덤 값으로 채운 텐서 생성

In [45]:
# 0<= ~ <1 범위의 임의의 숫자 1개 추출 >> rand (*size)
# rand(*size) : 가변인자 ==> 몇 차원일지 알 수 없음!
# '*' >> 가변인자(튜플형태) , '**' >> 키워드 파라미터(dict형태) , '*'들어올 인자가 몇개인지 모를때 확실히 정할수없을때

torch.manual_seed(1)

dataTS1 = torch.rand(3)             # 1차원 Vector
dataTS2 = torch.rand(2,3)           # 2차원 Maxtrix
dataTS3 = torch.rand(2,1,3)         # 3차원 3D Tensor

In [46]:
print(dataTS1, dataTS2, dataTS3, sep='\n\n')

tensor([0.7576, 0.2793, 0.4031])

tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])

tensor([[[0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635]]])


- Tensor생성 [3] torch.randn()

In [47]:
dataTS1 = torch.randn(3)             # 1차원 Vector
dataTS2 = torch.randn(2,3)           # 2차원 Maxtrix
dataTS3 = torch.randn(2,1,3)         # 3차원 3D Tensor

print(dataTS1, dataTS2, dataTS3, sep='\n\n')

tensor([-1.8349, -2.2149,  0.0436])

tensor([[ 1.3240, -0.1005,  0.6443],
        [ 0.5244,  1.0157,  0.2571]])

tensor([[[-0.9013,  0.8138,  0.3871]],

        [[ 0.5417,  0.6646,  0.3248]]])


- 차이 :  

- Tensor생성 [4] torch.randint()

In [48]:
torch.randint(1, 5, (3,5)) # 뒤에있는 값이 미만이다 > 포함이 안된다 

tensor([[2, 2, 1, 1, 2],
        [1, 1, 2, 4, 4],
        [3, 2, 1, 3, 4]])

In [51]:
dataTS1 = torch.randint(1, 46,(6,))
dataTS1

tensor([38, 44,  5, 39, 21, 18])

In [52]:
# 2D Vector
dataTS1 = torch.randint(1, 46,(4,6))
dataTS1

tensor([[ 8,  4, 21, 40, 45, 26],
        [22, 28, 18,  1, 11, 16],
        [35, 32, 17, 25,  6, 14],
        [38, 43, 19, 28, 28,  3]])