In [2]:
# 모듈 로딩
import torch                    # tensor, 일반 function
import torch.nn as nn           # nn관련 class, function
import torch.nn.functional as F   # nn관련 AL, LF, MF

In [3]:
## Model 설계
# 입력 피쳐수 : 3개 
# 출력 결과 : 회귀
# 손실 함수 : MSE, MAE, RMSE, ...
# 활성화 함수

## ANN 모델  입 : 출 
# 입력층 :   3개  10개  >> 10개 뉴런 ==> AF : ReLu
# 은닉층 :  10개  30개  >> 30개 뉴런 ==> AF : ReLu
# 출력층 :  30개   1개  >>  1개 뉴런 ==> AF : 회귀 linear >> pytorch X

class CustomModel(nn.Module):
    # 모델 구성 및 초기화 매서드
    def __init__(self):
        pass
    
    # 순방향 학습 매서드
    def forward(self, x):
        pass

    

In [6]:
## ANN 모델  입 : 출 
# 입력층 :   3개  10개  >> 10개 뉴런 ==> AF : ReLu
# 은닉층 :  10개  30개  >> 30개 뉴런 ==> AF : ReLu
# 출력층 :  30개   1개  >>  1개 뉴런 ==> AF : 회귀 linear >> pytorch X
mModel = nn.Sequential(
    nn.Linear(3,10),
    nn.ReLU(),
    nn.Linear(10,30),
    nn.ReLU(),
    nn.Linear(30,1)
)

In [ ]:
# 임시 데이터 ==> 2차원 (n,3) : n개 데이터  >> 왜 3이냐 >> 피쳐 3개라서
data = torch.FloatTensor([[10,20,30],[11,22,33]])
data.shape

target = torch.FloatTensor([[9,12]])

torch.Size([2, 3])

In [10]:
# 순방향 학습 ==> 내부적으로 forward() 메서드 호출
# [전달] [입력층] f1w1 + f2w2 + f3w3 + b >> ReLU() >> output 10개
#        [은닉층] >> o1w1 + o2w2 + o3w3 + ... + o10w10 + b >> ReLU() >> output 30개
#        [출력층] >> o1w1 + o2w2 + o3w3 + ... + o10w10 + b >> output 1개
mModel(data)

tensor([[0.0892],
        [0.1091]], grad_fn=<AddmmBackward0>)

In [16]:
mModel

Sequential(
  (0): Linear(in_features=3, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=30, bias=True)
  (3): ReLU()
  (4): Linear(in_features=30, out_features=1, bias=True)
)

In [ ]:
## 모델 구조 
# 입력층
input_layer = mModel.get_submodule('0')
input_layer.weight, input_layer.bias 

In [ ]:
# 은닉층
hid_layer = mModel.get_submodule('2')
hid_layer.weight, hid_layer.bias 

(Parameter containing:
 tensor([[-0.2760, -0.3115,  0.1684,  0.0517,  0.2634, -0.2857,  0.0415, -0.0105,
           0.1410, -0.1056],
         [-0.1900,  0.2869, -0.0731,  0.0542, -0.2077, -0.2583, -0.0088, -0.0810,
           0.1952,  0.1651],
         [ 0.1453,  0.1459, -0.1653, -0.0376, -0.0219, -0.0336,  0.0584, -0.2265,
           0.2044,  0.0933],
         [-0.1518, -0.1570, -0.2530, -0.2367, -0.2888,  0.1550,  0.1121,  0.2196,
          -0.0602,  0.1381],
         [-0.1947, -0.3049,  0.2563, -0.1565,  0.1623,  0.0859, -0.2840,  0.3162,
           0.1057,  0.0849],
         [-0.1869,  0.3017,  0.1021,  0.2253, -0.1282, -0.2654, -0.2289, -0.0879,
          -0.2183, -0.2721],
         [-0.1944, -0.1711, -0.2032, -0.0768, -0.1866, -0.1772, -0.1920,  0.3123,
           0.1971, -0.1263],
         [-0.1098, -0.0729,  0.1050, -0.2927, -0.2010, -0.0706, -0.0285, -0.2009,
           0.2148,  0.1495],
         [ 0.2555, -0.1680,  0.1332,  0.0496, -0.1956, -0.2746,  0.2971,  0.1622,
       

In [ ]:
# 모델 구조 
# 출력층 
output_layer = mModel.get_submodule('4')
output_layer.weight, output_layer.bias 

(Parameter containing:
 tensor([[-0.2760, -0.3115,  0.1684,  0.0517,  0.2634, -0.2857,  0.0415, -0.0105,
           0.1410, -0.1056],
         [-0.1900,  0.2869, -0.0731,  0.0542, -0.2077, -0.2583, -0.0088, -0.0810,
           0.1952,  0.1651],
         [ 0.1453,  0.1459, -0.1653, -0.0376, -0.0219, -0.0336,  0.0584, -0.2265,
           0.2044,  0.0933],
         [-0.1518, -0.1570, -0.2530, -0.2367, -0.2888,  0.1550,  0.1121,  0.2196,
          -0.0602,  0.1381],
         [-0.1947, -0.3049,  0.2563, -0.1565,  0.1623,  0.0859, -0.2840,  0.3162,
           0.1057,  0.0849],
         [-0.1869,  0.3017,  0.1021,  0.2253, -0.1282, -0.2654, -0.2289, -0.0879,
          -0.2183, -0.2721],
         [-0.1944, -0.1711, -0.2032, -0.0768, -0.1866, -0.1772, -0.1920,  0.3123,
           0.1971, -0.1263],
         [-0.1098, -0.0729,  0.1050, -0.2927, -0.2010, -0.0706, -0.0285, -0.2009,
           0.2148,  0.1495],
         [ 0.2555, -0.1680,  0.1332,  0.0496, -0.1956, -0.2746,  0.2971,  0.1622,
       