### 파이썬과 넘파이 모듈 차이점 

#### - 배열 구조 이해

In [1]:
import pandas as pd
import numpy as np

np.__version__

'2.0.0'

In [2]:
l = [[1,2,3],[4,5,6]]
type(l)

list

In [3]:
l[0], l[1]

([1, 2, 3], [4, 5, 6])

In [4]:
for i,a in enumerate(l):
        print(l[i])

[1, 2, 3]
[4, 5, 6]


In [5]:
for i,a in enumerate(l):
    for j,b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


In [6]:
print(np.ndarray)
np.ndarray.__name__

<class 'numpy.ndarray'>


'ndarray'

In [7]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
device
dtype
flags
flat
imag
itemset
itemsize
mT
nbytes
ndim
newbyteorder
ptp
real
shape
size
strides


In [8]:
t= (1,2,3,4)
b= np.array(t)


l = [1,2,3,4]
a = np.array(l)
a


array([1, 2, 3, 4])

In [9]:
type(a)

numpy.ndarray

In [10]:
type(b)

numpy.ndarray

In [11]:
print(a.data) 
a.data.obj

array([1, 2, 3, 4])

In [12]:
e=np.array(l, dtype=np.float32)
e

array([1., 2., 3., 4.], dtype=float32)

In [13]:
e.dtype

dtype('float32')

In [14]:
a2= np.array([[1,2,3],[4,5,6]])
print(a2.shape, 
      a2.ndim, 
      a2.dtype, 
      a2.itemsize, 
      a2.size, 
      a2.strides, sep='\n')

(2, 3)
2
int64
8
6
(24, 8)


In [15]:
np.ndarray.__bases__

(object,)

In [16]:
np.matrix.__bases__

(numpy.ndarray,)

#### - 넘파이 모듈의 함수 특징

In [17]:
(a != 0).any

<function ndarray.any>

In [18]:
np.any

<function any at 0x0000029F51F21270>

In [19]:
np.ndarray.any is np.core.fromnumeric.any

C:\Users\KDP-23\AppData\Local\Temp\ipykernel_4452\3956599824.py:1: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.fromnumeric.
  np.ndarray.any is np.core.fromnumeric.any


False

In [20]:
np_ = set(dir(np))
np_

{'False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a

In [21]:
nd_ = set(dir(np.ndarray))
nd_

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__

In [22]:
npd_ = np_ & nd_
npd_

{'__dir__',
 '__doc__',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'cumprod',
 'cumsum',
 'diagonal',
 'dot',
 'dtype',
 'imag',
 'max',
 'mean',
 'min',
 'ndim',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'sum',
 'swapaxes',
 'take',
 'trace',
 'transpose',
 'var'}

In [23]:
len(npd_)

48

In [24]:
count = 0
for i in list(npd_):
    count +=1
    print(i, end=" ")
    if count% 5 == 0 :
        print()


mean clip astype cumprod conj 
dot argmin size nonzero argpartition 
compress dtype take imag conjugate 
sum copy prod real trace 
searchsorted __doc__ choose put reshape 
shape std cumsum __dir__ squeeze 
sort diagonal resize argsort swapaxes 
ravel ndim partition var argmax 
repeat max round all min 
transpose ptp any 

In [25]:
a = dir(np)
np.ufunc

numpy.ufunc

In [26]:
# count=0
# for i in a :
#     if i == "Tester":
#         continue
#     if type(np.__dict__[i]) == np.ufunc:
#         print(i, end=" ")
#         count+=1
#         if count % 5 ==0:
#             print()

In [27]:
a= np.arange(6,10)
b= np.arange(10, 14)
a

array([6, 7, 8, 9])

In [28]:
b

array([10, 11, 12, 13])

In [29]:
c= a*b # 각 자리의 인덱스끼리 곱셈
c

array([ 60,  77,  96, 117])

In [30]:
a2 = np. array([1,2,3,4])
a2

array([1, 2, 3, 4])

In [31]:
a2 = a2.reshape(2,2)
a2

array([[1, 2],
       [3, 4]])

In [32]:
np.sum(a2)

np.int64(10)

In [33]:
np.sum(a2, axis=0) # >> 여기 야는 이상하게 axis=0은 열끼리

array([4, 6])

In [34]:
np.sum(a2, axis=1) # >> axis=1은 행끼리 더하기 진행

array([3, 7])

In [35]:
a=np.array([4,5])
b=np.array([3,4,5])
print( a.shape, b.shape, sep='\n')

(2,)
(3,)


In [36]:
try:
    a+b
except Exception as e :
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 
