### 다차원 배열의 구조 변경하기

#### - 변경 및 결합 주요 함수

In [3]:
import pandas as pd
import numpy as np

##### >> 배열의 형상 변경

In [4]:
x = np.arange(16)
x 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
x1= x.reshape(2,8)
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [6]:
# 원소의 개수가 안 맞으면 에러 발생
try : 
    x2 = x.reshape(4,5)
except Exception as e : 
    print(e)

cannot reshape array of size 16 into shape (4,5)


In [7]:
x3 = x.reshape(2,2,4)
x3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
y =  np.arange(20)
y                      

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
y1 = y.reshape(4,-1)
y1                   # -1로 지정하면 나머지 형상은 자동으로 세팅

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
try : 
    y2 = x.reshape(-1,4)
except Exception as e : 
    print(e)

In [20]:
y2                  # 반대도 적용가능

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

##### >> 배열의 크기 변경

In [23]:
# 동일 차원에서 크기만 확장

a= np.arange(4)
a

array([0, 1, 2, 3])

In [24]:
np.resize(a,8)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [25]:
np.append(a,a)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [26]:
np.resize(a,11) # np.resize(해당 행렬, 원하는 크기)

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2])

In [28]:
b= np.arange(7)
np.append(a,b) # np.append(합치고싶은 행렬들)

array([0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6])