In [2]:
import numpy as np
import pandas as pd

### 행렬(Matrix) 알아보기

In [3]:
A = np.array([[43],[44]])
type(A)

numpy.ndarray

In [4]:
A

array([[43],
       [44]])

In [5]:
print(A.dtype, A.ndim, A.shape, sep='\n')

int64
2
(2, 1)


In [47]:
c1 = np.array([[1,2,4],[2,4,8],[3,4,5]])
np.linalg.matrix_rank(c1) # 현재 값이 [0][1] 비슷 > 2출력 

np.int64(2)

In [52]:
c1

array([[1, 2, 4],
       [2, 4, 8],
       [3, 4, 5]])

In [51]:
np.linalg.det(c1)

np.float64(0.0)

In [53]:
c1[0]*2 - c1[1] # c1에 [0][1]이 2곱하면 되서 비슷 >> 위에 matrix_rank 2출력

array([0, 0, 0])

In [50]:
c2 = np.array([[1,3,4],[1,8,5],[2,3,4]])
np.linalg.matrix_rank(c2)

np.int64(3)

In [54]:
np.linalg.det(c2)

np.float64(-17.0)

In [56]:
np.linalg.matrix_rank(c2.T)

np.int64(3)

In [57]:
# 축 알아보기
A = np.array([[2,3],[4,5]])
print(A.sum(), A.sum(axis=0), A.sum(axis=1), sep='\n')

14
[6 8]
[5 9]


In [70]:
C = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
C

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [71]:
C.ndim

3

In [72]:
C.shape

(2, 2, 2)

In [65]:
C[0]

array([[1, 2],
       [3, 4]])

In [66]:
C[1]

array([[5, 6],
       [7, 8]])

In [67]:
C.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [68]:
C.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [69]:
C.sum(axis=2)

array([[ 3,  7],
       [11, 15]])

In [79]:
# 확장 및 축소
## 차원 확장
x= np.array([1,2])
x , x.shape

(array([1, 2]), (2,))

In [80]:
y = np.expand_dims(x, axis=1)
y , y.shape

(array([[1],
        [2]]),
 (2, 1))

In [81]:
z= np.expand_dims(x, axis=0)
z, z.shape

(array([[1, 2]]), (1, 2))

In [82]:
## 차원 축소
x= np.array([[1,4,5],[4,5,6],[7,8,9]])
x, x.shape

(array([[1, 4, 5],
        [4, 5, 6],
        [7, 8, 9]]),
 (3, 3))

In [83]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [84]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [85]:
x # >> 축소한다고해서 본 데이터는 사라지지 않음

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

### 행렬 종류 알아보기

In [ ]:
# 정사각행렬

In [ ]:
# 대각행렬

In [ ]:
# 삼각행렬

In [86]:
# 대칭행렬

In [87]:
# 치환행렬

In [ ]:
# 직교행렬
# 교행렬은 자기 자신의 행렬과 전치행렬을 행렬곱으로 계산하면 단위행렬이 나옵니다. 직교
# 행렬의 전치행렬은 곧 역행렬입니다.

In [ ]:
# 전치행렬
# 기존의 행과 열을 서로 바꾼 행렬, 위 첨자 T를 사용

In [7]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
x[[3,0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [9]:
x[[1,2], [2,3]]

array([ 6, 11])

In [10]:
x[[1,2],2]

array([ 6, 10])

In [11]:
a=np.array([[2,3,4,5],[8,9,0,1]])
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [12]:
type(np.ix_)

numpy._ArrayFunctionDispatcher

In [13]:
a[np.ix_([0,1],[0,1])]

array([[2, 3],
       [8, 9]])

In [14]:
b = np.arange(300).reshape(25,12)
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167],
       [168, 169, 170, 171, 172, 1

In [15]:
x= np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
a = x[1:, 1:]
a

array([[4, 5],
       [7, 8]])

In [17]:
np.may_share_memory(x,a)

True

In [18]:
a=np.reshape(np.arange(10), (2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
b= np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
c= a[[1,0,1], np.newaxis]
c

array([[[5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [21]:
c.shape

(3, 1, 5)

In [22]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
x[1,2]=20
x

# arr[index] = value

array([[ 0,  1,  2],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [24]:
posl = [1,5]
x.take(posl)

array([ 1, 20])

In [25]:
x

array([[ 0,  1,  2],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [26]:
np.choose(1,x) 

array([ 3,  4, 20])

In [27]:
x=np.arange(1,4)
x1=x.reshape(1,3)
x2 = x[np.newaxis,]

y= np.arange(1,4)
y1 = y.reshape(3,1)
y2 = y[:,np.newaxis]

np.broadcast_arrays(x1,y1)

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]))

In [28]:
import numpy as np

a = np.array([[1, 2, 3]])
b = np.array([[4], [5]])

result = np.broadcast_arrays(a, b)
result

(array([[1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5]]))

In [29]:
x1

array([[1, 2, 3]])

In [30]:
y1

array([[1],
       [2],
       [3]])

In [31]:
x1+y1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [32]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
np.einsum("ab->ba",A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
x = np.arange(16)
y1 = x.reshape(4,-1)
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
y = np.arange(4)
y2= y.resize((4,4))
y2

In [37]:
x=np.arange(3)
y=np.arange(4)

x_,y_ = np.meshgrid(x,y)
x_

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [38]:
y_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [39]:
x_1 = x.reshape(1,-1)
np.concatenate([x_1,x_1,x_1,x_1])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [40]:
x = np.array([[[0],[1],[2]]])
x

array([[[0],
        [1],
        [2]]])

In [41]:
x.shape

(1, 3, 1)

In [42]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)
b = np.vstack([a,a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [43]:
x,y = np.split(b,[3])
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)

In [44]:
y

array([[4, 5, 6]], dtype=int32)

In [45]:
w,z = np.split(b,[2])
w

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [46]:
z

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)