In [147]:
import numpy as np
import pandas as pd

### 배열 할당과 검색

In [148]:
a = np.array([[1,2], [3,4]])
b = a
a

array([[1, 2],
       [3, 4]])

In [149]:
b

array([[1, 2],
       [3, 4]])

In [150]:
b[0] = 999 # b에 값을 변경하면 a에도 영향을 끼친다
a

array([[999, 999],
       [  3,   4]])

In [151]:
b

array([[999, 999],
       [  3,   4]])

----------------------------------------

In [152]:
f = np.array([[1,2], [3,4]])
e = f.copy() # copy로 따로 두면 원데이터에 영향을 미치진 않는다.
e[1] = 100
f

array([[1, 2],
       [3, 4]])

In [153]:
e

array([[  1,   2],
       [100, 100]])

In [154]:
g = f[:]  # 슬라이싱도 영향을 받는다 
g

array([[1, 2],
       [3, 4]])

In [155]:
g[0]=100
g

array([[100, 100],
       [  3,   4]])

In [156]:
f

array([[100, 100],
       [  3,   4]])

In [157]:
l = list(range(1,10))
index= 1
l.__getitem__(index)

2

In [158]:
index = slice(1,3)
l.__getitem__(index)

[2, 3]

In [159]:
a= np.array([1,2,3,4,5,6,7])
index = 1
a.__getitem__(index)

np.int64(2)

In [160]:
index = slice(1,7)
a.__getitem__(index)

array([2, 3, 4, 5, 6, 7])

In [161]:
index = [1]
a.__getitem__(index)

array([2])

In [162]:
index = a < 4 
index

array([ True,  True,  True, False, False, False, False])

In [163]:
a.__getitem__(index)

array([1, 2, 3])

### 선형 대수 기본 알아보기

In [164]:
# 스칼라
a= np.array(43)
print(type(a))
a

<class 'numpy.ndarray'>


array(43)

In [165]:
print(a.ndim , a.shape, a.dtype, a==43, sep= '\n')

0
()
int64
True


In [166]:
# 벡터 - 1차원

v = np.array ([43])
print(type(v), v, v.ndim, v.shape, sep='\n')

<class 'numpy.ndarray'>
[43]
1
(1,)


In [167]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
v.dtype

dtype('int64')

In [169]:
v1 = np.arange(10.5, 20.5, 0.5) # np.arange(시작, 끝, 간격) # 끝은 포함 X
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [170]:
print(v1.dtype, v1.size, sep='\n')

float64
20


In [171]:
la =  np.linspace(1,10,10)
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [172]:
la =  np.linspace(1,10,10, endpoint=False) # 종점 지정가능
la

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [173]:
la.dtype

dtype('float64')

In [174]:
la1 = np.linspace(1,10,10, endpoint= False, retstep=True) # 간격 값 확인가능
la1

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), np.float64(0.9))

In [175]:
la2 = np.linspace(0,2,4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [176]:
lo = np.logspace(0,2,4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [177]:
for i in la2:
    print(np.power(10,i))

1.0
4.641588833612778
21.544346900318832
100.0


In [218]:
# 벡터 크기
# 벡터는 크기와 방향을 가집니다. 
# 다차원 배열로 표시할 때 크기에 대해 계산 가능. 
# 벡터의 크기는 각 원소의 제곱한 후에 합산한 것을 제곱근을 처리
v= np.arange(3,5)
v

array([3, 4])

In [219]:
np.hypot(v[0],v[1]) # 백터 크기 구하는 hypot(좌표값)

np.float64(5.0)

In [221]:
v_p = np.power(v,2) # (,) 안에 숫자는 제곱수를 나타내줌
v_p

array([ 9, 16])

In [222]:
v_r = np.sqrt(np.sum(v_p))
v_r

np.float64(5.0)

In [224]:
# np.power() 예시
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 2, 1])

result = np.power(a, b) # >> a의 인덱스에 맞는 숫자가 제곱수로 올라감
print(result)

[1 8 9 4]


In [225]:
np.linalg.norm(v) # linalg 모듈에 norm 함수를 사용

np.float64(5.0)

#### 표준 단위 벡터

In [ ]:
# 표준 단위벡터는 위치는 원소 중에 하나가 1, 나머지 원소 0
# 표준 단위벡터의 표기는 e에 첨자를 부여, 인덱스의 위치에 해당하는 원소만 1

In [227]:
e1 = np.array([1,0,0])
np.linalg.norm(e1)

np.float64(1.0)

In [228]:
e2 = np.array([0,1,0])
np.linalg.norm(e1)

np.float64(1.0)

In [229]:
e3 = np.array([0,0,1])
np.linalg.norm(e1)

np.float64(1.0)

#### 단위 벡터

In [232]:
v_3 = np.array([1,2,3])
v_3_n = np.linalg.norm(v_3)
v_3_n

np.float64(3.7416573867739413)

In [234]:
v_3_u= v_3 / v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [235]:
np.linalg.norm(v_3_u)

np.float64(1.0)

#### 벡터의 상등

In [ ]:
# 벡터의 상등(equality)은 크기와 방향이 같을 경우를 뜻함
# 크기는 같지만 방향이 다르면 상등x

In [236]:
a= np.arange(3,5)
b= np.arange(3,5)
np.array_equal(a,b)

True

In [239]:
a1= np.linalg.norm(a)
b1 = np.linalg.norm(b)

a1==b1

np.True_

#### 벡터의 거리

In [240]:
c= np.arange(10,13)
d = np.arange(0.3)
np.sqrt(np.sum(np.square(c-d)))

np.float64(19.1049731745428)

In [241]:
np.linalg.norm(c-d)

np.float64(19.1049731745428)

In [178]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [179]:
x[[3,0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [180]:
x[[1,2], [2,3]]

array([ 6, 11])

In [181]:
x[[1,2],2]

array([ 6, 10])

In [182]:
a=np.array([[2,3,4,5],[8,9,0,1]])
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [183]:
type(np.ix_)

numpy._ArrayFunctionDispatcher

In [184]:
a[np.ix_([0,1],[0,1])]

array([[2, 3],
       [8, 9]])

In [185]:
b = np.arange(300).reshape(25,12)
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131],
       [132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167],
       [168, 169, 170, 171, 172, 1

In [186]:
x= np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [187]:
a = x[1:, 1:]
a

array([[4, 5],
       [7, 8]])

In [188]:
np.may_share_memory(x,a)

True

In [189]:
a=np.reshape(np.arange(10), (2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [190]:
b= np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [191]:
c= a[[1,0,1], np.newaxis]
c

array([[[5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [192]:
c.shape

(3, 1, 5)

In [193]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [194]:
x[1,2]=20
x

# arr[index] = value

array([[ 0,  1,  2],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [195]:
posl = [1,5]
x.take(posl)

array([ 1, 20])

In [196]:
x

array([[ 0,  1,  2],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [197]:
np.choose(1,x) 

array([ 3,  4, 20])

In [198]:
x=np.arange(1,4)
x1=x.reshape(1,3)
x2 = x[np.newaxis,]

y= np.arange(1,4)
y1 = y.reshape(3,1)
y2 = y[:,np.newaxis]

np.broadcast_arrays(x1,y1)

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]))

In [199]:
import numpy as np

a = np.array([[1, 2, 3]])
b = np.array([[4], [5]])

result = np.broadcast_arrays(a, b)
result

(array([[1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5]]))

In [200]:
x1

array([[1, 2, 3]])

In [201]:
y1

array([[1],
       [2],
       [3]])

In [202]:
x1+y1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [203]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [204]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [205]:
np.einsum("ab->ba",A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [206]:
x = np.arange(16)
y1 = x.reshape(4,-1)
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [207]:
y = np.arange(4)
y2= y.resize((4,4))
y2

In [208]:
x=np.arange(3)
y=np.arange(4)

x_,y_ = np.meshgrid(x,y)
x_

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [209]:
y_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [210]:
x_1 = x.reshape(1,-1)
np.concatenate([x_1,x_1,x_1,x_1])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [211]:
x = np.array([[[0],[1],[2]]])
x

array([[[0],
        [1],
        [2]]])

In [212]:
x.shape

(1, 3, 1)

In [213]:
a = np.linspace(1,6,6, dtype=np.int32).reshape(2,3)
b = np.vstack([a,a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [214]:
x,y = np.split(b,[3])
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)

In [215]:
y

array([[4, 5, 6]], dtype=int32)

In [216]:
w,z = np.split(b,[2])
w

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [217]:
z

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)